const ShopActionTypes = {
    FETCH_COLLECTIONS_START:'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS:'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAIL:'FETCH_COLLECTIONS_FAIL',
    SHOW_ITEM:'SHOW_ITEM',

    UPDATE_RELATED_PRODUCTS:'UPDATE_RELATED_PRODUCTS',

    GET_COLLECTION_FROM_FIREBASE_START:'GET_COLLECTION_FROM_FIREBASE_START',
    GET_COLLECTION_FROM_FIREBASE_SUCCESS:'GET_COLLECTION_FROM_FIREBASE_SUCCESS',
    GET_COLLECTION_FROM_FIREBASE_FAILURE:'GET_COLLECTION_FROM_FIREBASE_FAILURE'
};

export default ShopActionTypes;