const ShopActionTypes = {
    FETCH_COLLECTIONS_START:'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS:'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAIL:'FETCH_COLLECTIONS_FAIL',
    SHOW_ITEM:'SHOW_ITEM'
};

export default ShopActionTypes;