const ShopActionTypes = {
    FETCH_COLLECTIONS_START:'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS:'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAIL:'FETCH_COLLECTIONS_FAIL',
    SHOW_ITEM:'SHOW_ITEM',

    GET_COLLECTION_TO_RELATED:'GET_COLLECTION_TO_RELATED',
    UPDATE_RELATED_PRODUCTS:'UPDATE_RELATED_PRODUCTS'
};

export default ShopActionTypes;